# To run: $ conda env create -f environment.yml
name: phase_unwrap
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - cudatoolkit=11.0
    - tensorflow=2.8
    - keras
    - numpy
    - matplotlib
    - ipywidgets
    - tqdm
    - keras-preprocessing
    - scikit-learn
    - pip:
      - opencv-contrib-python-headless==4.4.0.40